# Generated by Django 4.2.27 on 2026-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
